# Generated by Django 5.2.5 on 2025-08-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_book_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='note',
            name='modified_at',
        ),
        migrations.AddField(
            model_name='book',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='highlight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
