# Generated by Django 5.2.5 on 2025-08-17 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_remove_book_modified_at_remove_note_modified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
