# Generated by Django 5.2.5 on 2025-08-17 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_note_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='book_id',
            new_name='book',
        ),
    ]
